on: push
name: 🚀 Publication
jobs:
    publish:
        name: 🎉 Déploiment sur GitHub
        runs-on: ubuntu-latest
        steps:
            - name: 🚚 Obtention du dernier code
              uses: actions/checkout@v3

            - name: 📂 Synchronisation des fichiers
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4
              with:
                  server: ${{secrets.SERVER_FTP}}
                  username: ${{secrets.USERNAME_FTP}}
                  password: ${{secrets.PASSWORD_FTP}}
                  local-dir: ./
                  server-dir: ./

    npm-install:
        name: 📦 Installation des dépendances
        runs-on: ubuntu-latest
        needs: publish
        steps:
            - name: 💻 Configuration de Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18
            - name: 📂 Accès en SSH au serveur et exécution de npm install
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{secrets.SERVER_SSH}}
                  username: ${{secrets.USERNAME_SSH}}
                  password: ${{secrets.PASSWORD_SSH}}
                  port: 22
                  script: npm install;